---
title: "edad"
format: html
editor: visual
---

## Edad

```{r}
library(fitdistrplus)
library(dplyr)
```

```{r}
table(encuesta$Age)
```

```{r}
barplot(table(encuesta$Age))
```

```{r}
encuesta$ModifiedAge <- encuesta$Age

numeros = c("0", "1", "2", "3", "4", "5", "6")

for (i in 0:length(ages)) {

encuesta$ModifiedAge <- ifelse(encuesta$ModifiedAge == ages[i], numeros[i], encuesta$ModifiedAge)

}
```

```{r}
ages <- c("Under 18 years old", "18-24 years old", "25-34 years old", "45-54 years old", "55-64 years old", "65 years or older")

encuesta$ModifiedAge <- 0

encuesta$ModifiedAge <- ifelse(
  encuesta$Age == "Under 18 years old", 0, 
  ifelse(encuesta$Age == "18-24 years old", 1, 
    ifelse(encuesta$Age == "25-34 years old", 2, 
      ifelse(encuesta$Age == "35-44 years old", 3,
        ifelse(encuesta$Age == "45-54 years old", 4,
          ifelse(encuesta$Age == "55-64 years old", 5, 
            ifelse(encuesta$Age == "65 years or older", 6, encuesta$ModifiedAge)))))))

for (i in 1:nrow(encuesta)){
  for (j in 1:length(ages)){
    if (encuesta$Age[i] == ages[j]){
      encuesta$ModifiedAge[i] <- j
    }
  }
}
```

```{r}
hist(encuesta$ModifiedAge, 
     breaks=6,
     main = "Frecuencia Modified Age")
```

```{r}
encuesta %>% group_by(ModifiedAge) %>% count() -> probModifiedAge
probModifiedAge %>% rename(Frecuencia = n) -> probModifiedAge
```

```{r}
probModifiedAge$ProbabilidadAtomica <- probModifiedAge$Frecuencia / nrow(encuesta)
```

```{r}
probModifiedAge
```

```{r}
fit <- fitdist(encuesta$ModifiedAge, "pois")
summary(fit)
```

```{r}
plot(probModifiedAge$ModifiedAge, 
     probModifiedAge$ProbabilidadAtomica,
     type = "h",
     col = "red",
     lwd = 2)

lambda <- fit$estimate
x <- 0:6
densidad <- dpois(x, lambda)

# plot(x, densidad, type = "h", lwd = 2, col = "blue",
#     xlab = "Valores de x", ylab = "Densidad de probabilidad",
#     main = "Distribución Poisson")


```
