---
title: "Jeff"
format: html
editor: visual
---

## Item 2

Lenguajes que causan mas los problemas mentales:

-   Autismo: Crystal Lua Rust

-   Aprendizaje: APL Lua Assembly

-   Emocionales: Erlang Lua LISP

-   Memoria: Erlang Crystal Lua

-   Ansiedad: SAS Ruby Lua

    **E1: Usa uno o más de los lenguajes problemáticos**

```{r}
list <- c('Crystal', 'Lua', 'Rust', 'APL', 'Assembly', 'Erlang', 'LISP', 'SAS')

e1 = encuesta$Crystal | encuesta$Lua | encuesta$Rust | encuesta$APL | encuesta$Assembly | encuesta$Erlang | encuesta$LISP | encuesta$SAS

probE1 = sum(e1)/nrow(encuesta)
probE1
```

**probE2: Sufren de problemas mentales**

```{r}
# Crear una columna en el dataframe 'encuesta' que cuente la cantidad de problemas mentales (valores TRUE)
encuesta$num_problemas_mentales <- rowSums(encuesta[, c("Memoria", "Aprendizaje", "Autismo", "Ansiedad", "Emocional")])

# Calcular la probabilidad de que alguien sufra de 3 o más problemas mentales
probE2 <- sum(encuesta$num_problemas_mentales > 0) / nrow(encuesta)

# Imprimir el resultado
probE2
```

**E1 y probE2**

```{r}
total = data.frame(e1, encuesta$num_problemas_mentales)
probe1probE2 = nrow(total[total$e1 == TRUE & total$encuesta.num_problemas_mentales > 0,])/nrow(total)
probe1probE2

total$encuesta.num_problemas_mentales = total$encuesta.num_problemas_mentales > 0

mosaicplot(table(total$e1, total$encuesta.num_problemas_mentales), main = "Problemas mentales y lenguajes problemáticos")
```

**Comprobamos con las fórmulas de probabilidades**

```{r}
probE2dE1 <- probe1probE2/probE1
cat("P(E2): ", probE2)
cat("\nP(E2|E1): ", probE2dE1)
cat("\nP(E1|E2) - P(E2)",  probE2 - probE1)

cat("\nP(E1 interseccion E2)", probe1probE2)
cat("\nP(E2)*P(E1)",probE1 * probE2)
```
