---
title: "Estudio sobre la relación entre las tecnologías que usan los desarrolladores en su trabajo y su salud mental"
author: '**Grupo 7** 
  Integrantes: 
    Isabella Romero, 
    César Perales, 
    Jeffrey Monja,
    Edwid Pinto,
    Sebastián Rodriguez'
date: "30 de junio del 2023"
output:
  ioslides_presentation:
    css: 'styles.css'
    widescreen: yes
---

## Objetivos

### Objetivo principal

Demostrar que la salud mental del programador depende, en parte, del lenguaje de programación que escoja para trabajar.

### Objetivos secundarios

-   Demostrar que la popularidad de un lenguaje de programación no significa que trabajar con este brinde un mejor estado de salud mental.

-   Encontrar una relación entre el acceso a información del lenguaje de programación escogido por el programador y su salud mental.

-   Encontrar una relación entre el salario que brinda el lenguaje de programación que usan los desarrolladores con su salud mental.

-   Demostrar la relación entre el sistema operativo utilizado en el ámbito profesional y la salud mental de los individuos, y encontrar una posible asociación entre los problemas mentales y el tipo de sistema operativo.
